### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by spyda90** [Acellera/acegen-open#26]
Hi,

Sorry for bothering you with a so easy question. I was going through the installation of acegen.

When you specify to run:

```
pip3 install tqdm wandb hydra-core
cd acegen-open
pip install ./
```
The acegen-open folder is not there after the first command (obviously resulting in a  error "cd: acegen-open: No such file or directory" if running the second one).

How should I proceed?

Thank you in advance.

**Comment by albertbou92** [comment]
Hi [spyda90](https://github.com/spyda90)! 

Thank you looking into out project.

did you clone the repo?

Before running  `cd acegen-open ` you need to run `git clone git@github.com:Acellera/acegen-open.git`

Maybe it is not clear enough in our README, sorry about that. I will update it.

**Comment by spyda90** [comment]
Thank you!
