### ISSUE TITLE
De Novo: YAML file

### ISSUE THREAD

**Issue by spyda90** [Acellera/acegen-open#27]
Hi again,

My purpose is to generate de_novo cpd starting from one hit molecule. 

Which is the best way to go and how should I edit the configuration YAML file? I was looking for tutorial for this but I was not able to find it out.

Thank you again!

**Comment by MorganCThomas** [comment]
Hello, what do you mean by de novo? You wish to keep the current molecule and decorate it? Or you wish to generate completely new molecules but in a 'similar' area of chemical space?

**Comment by albertbou92** [comment]
All generative RL scripts need a reward function that guides them. 

You could define a reward function that captures what you want: to generate molecules similar to your hit. Maybe something like this:

```
from rdkit import Chem
from rdkit.Chem import AllChem, DataStructs

def get_fingerprint(smiles):
    """Generate a molecular fingerprint from a SMILES string."""
    mol = Chem.MolFromSmiles(smiles)
    return AllChem.GetMorganFingerprintAsBitVect(mol, 2, 2048) if mol else None

def compute_similarities(target_smiles="CCO", candidate_smiles_list=None):
    """Compute similarity scores between a target molecule and a list of candidate molecules.
    
    Parameters:
    - target_smiles (str): SMILES string of the target molecule. Defaults to "CCO" (Ethanol).
    - candidate_smiles_list (list of str): List of SMILES strings for candidate molecules. Defaults to an empty list.
    
    Returns:
    - list of float: List of similarity scores between the target molecule and each candidate molecule.
    """
    if candidate_smiles_list is None:
        candidate_smiles_list = []
    
    target_fp = get_fingerprint(target_smiles)
    if target_fp is None:
        raise ValueError("Invalid target SMILES string")
    
    similarity_scores = []
    for smiles in candidate_smiles_list:
        if smiles == target_smiles:
            similarity_scores.append(0.0)
        else:
            candidate_fp = get_fingerprint(smiles)
            similarity = DataStructs.TanimotoSimilarity(target_fp, candidate_fp) if candidate_fp else 0.0
            similarity_scores.append(similarity)
    
    return similarity_scores
```

Then, follow the tutorial in https://github.com/Acellera/acegen-open/blob/main/tutorials/adding_custom_scoring_function.md too see how to use it in our scripts.

then, you could try running for example the reinvent de novo script to generate similar molecules
python scripts/reinvent/reinvent.py --config-name config_denovo

**Comment by albertbou92** [comment]
I actually tried running the script myself for with the target SMILE "CC(C)(C1=CC(=CC(=C1)C(CO)NC(C)C(O)=O)O)O" and got the following results:

<img width="553" alt="Screenshot 2024-05-17 at 20 07 51" src="https://github.com/Acellera/acegen-open/assets/23138441/e71f829d-442f-407e-814c-c1f7ac4e15da">

smiles                                                                                                            score_custom_scoring.compute_similarities_to_target
c1c(C(NC(C(=O)O)C)CO)cc(O)cc1O                                                          0.743590
Oc1cc(C(CO)NC(C(O)=O)C)cc(O)c1                                                          0.743590
c1(C(CO)NC(C(=O)O)C)cc(O)cc(O)c1                                                       0.743590
c1(C(F)(F)F)cc(C(CO)NC(C)C(O)=O)cc(C(C)(O)C)c1                               0.750000
c1c(C(CO)NC(C(O)=O)C)cc(C(C)(O)C)cc1C(F)(F)F                                  0.750000
OC(C)(C(C)(O)C)c1cc(C(CO)NC(C)C(=O)O)cc(C(C)(O...                         0.750000
c1(C(F)(F)F)cc(C(CO)NC(C)C(O)=O)cc(O)c1                                             0.767442
c1(C(F)(F)F)cc(C(NC(C(=O)O)C)CO)cc(O)c1                                             0.767442
c1(C(NC(C(=O)O)C)CO)cc(C(C(F)(F)F)(O)C)cc(O)c1                                0.777778
c1c(C(NC(C(=O)O)C)CO)cc(C(C)(C)C)cc1C(C)(O)C                                 0.785714
OC(C)(C)c1cc(C(NC(C(=O)N)C)CO)cc(O)c1                                              0.790698
CC(C)(C)c1cc(C(CO)NC(C(O)=O)C)cc(O)c1                                              0.829268
c1(C(CO)NC(C(O)=O)C)cc(C(C)(O)C)cc(C(C)(O)C)c1                              0.846154
c1(C(CO)NC(C(=O)O)C)cc(C(C)(O)C)cc(C(C)(O)C)c1                              0.846154
c1(C(CO)NC(C(O)=O)C)cc(C(C)(O)C)cc(C(C)(O)C)c1                              0.846154
c1(O)cc(C(C)(O)C)cc(C(CO)NC(C)C(=O)O)c1                                           1.000000
c1(C(CO)NC(C(O)=O)C)cc(C(C)(O)C)cc(O)c1                                           1.000000
c1(C(C)(O)C)cc(C(NC(C(=O)O)C)CO)cc(O)c1                                           1.000000
c1(C(NC(C(=O)O)C)CO)cc(C(C)(O)C)cc(O)c1                                           1.000000
c1(C(CO)NC(C(O)=O)C)cc(C(C)(O)C)cc(O)c1                                           1.000000

**Comment by spyda90** [comment]
Thank you, I will try it on Monday!


________________________________
