### ISSUE TITLE
DPO implementation?

### ISSUE THREAD

**Issue by philippguevorguian** [Acellera/acegen-open#29]
This is a very interesting and useful project. Given that the framing of molecular optimization problems is relatively straightforward, I don't see why direct preference optimization couldn't be applied. It's a simpler framework (no actor/critic required) and more computationally effecient. Are there any plans to implement DPO here?

**Comment by albertbou92** [comment]
Hello!  I am happy to look into implementing DPO if there is interest in it.

However, as I understand, DPO solves the problem of having to train a reward model and "only" requires good and bad examples (ranked) given a promp. In our case, we don't really use human feedback data, we have regular reward functions, not based on a neural network. So we would require I guess a dataset with the positive and negative labels.

Maybe given an input, it would be possible to generate 2 molecules. Then label the highest scoring molecules the positive sample and the other the negative sample. But again, given that we already have a scoring function, not sure if it would improve the results.

Is sth like that what you had in mind?

**Comment by philippguevorguian** [comment]
I think the benefit of being able to model human feedback is (in my opinion) a non-trivial advantage of DPO in the applied case, even though datasets don't exist now. Although, the relative simplicity and compute-efficiency of DPO are what I'm primarily interested in, so I'm looking to create positive-negative pairs by comparing scoring function values exactly as you say. 

With that being said, I definitely agree that there are some issues with the approach, most pertintent of which (which you identify) is that the differences between rewards for pairs are not used in classic DPO. However, there is a nice paper which addresses this problem: [Direct Preference Optimization with an Offset](https://arxiv.org/pdf/2402.10571) from ETH Zurich, which shows promising results and could be easily integrated in the future, if DPO is already implemented. In general, this is an area of active research, so I think it's safe to assume even better formulations will appear soon. 

The other issue is that of feasibility of integration into the ace-gen codebase, given that this requires working with pairs (or a sequence of pairs) of molecules rather than one molecule at a time. I can't speak to how difficult this will be, so I understand if this is a low priority item. For that reason, I would also be willing to help with the implementation if contributing is supported. From what I understand this would involve creating a new module in the scripts folder?

**Comment by albertbou92** [comment]
Hello! Of course, contributions are super welcome :)

As you mentioned, DPO would go in another scripts folder. 
I gave it a shot already, it seemed easy to adapt, check out this script:
https://github.com/Acellera/acegen-open/tree/dpo/scripts/dpo

I went for the most straightforward approach, generating a bunch of molecules, ranking them by score, and then selecting the top 50% as positive examples and the rest as negative examples.

Feel free to look at the code and do a PR against the DPO branch if you think there is any error. Or if any extension would make sense. Once we feel like the approach is correct we can merge. 

 I tested it a bit and seems to learn fine.

![Uploading Screenshot 2024-05-27 at 12.04.52.png…]()

Let me know what do you think.

**Comment by philippguevorguian** [comment]
This is great, thanks! I'll try to replicate these results first. Then, I'd just like to add some configuration for selecting positive and negative examples, as well as the offset DPO variant.

**Comment by albertbou92** [comment]
Awesome! thanks a lot
