### ISSUE TITLE
[BUG] Latest version of TorchRL and TensorDict aren't compatible

### ISSUE THREAD

**Issue by MorganCThomas** [Acellera/acegen-open#52]
# Error
`RuntimeError: tensor shape is incompatible with dest shape, got: tensor.shape=torch.Size([128]), dest=torch.Size([3, 512])`

# Reproduce
```
acegen-open/tests/check_scripts/run_reinforce_denovo.sh
```
# Environment
torchrl==0.6.0 (5244a90)
tensordict==0.6.0 (8c65dcb)

# Discussion
Seems this is a problem with the TransformedEnv adding LSTM/GRU primers, previously the batch size was automatically added as the leading dimension which doesn't seem to happen with this update.

**Comment by albertbou92** [comment]
I am able to reproduce the error

**Comment by albertbou92** [comment]
https://github.com/pytorch/rl/pull/2521

**Comment by stanleyjs** [comment]
Error occurs in torchrl 0.6.0 and tensordict 0.6.2.

I was able to workaround by rolling back both.

**Comment by MorganCThomas** [comment]
This hasn't been fixed in tensordict yet @stanleyjs. But it is prompting me to specify a requirement version of torchrl and tensordict for acegen. I'll look into doing this ASAP.

**Comment by MorganCThomas** [comment]
For now, I've created a requirements.txt file with the versions of torchrl and tensordict acegen has been tested with.  #54

**Comment by MorganCThomas** [comment]
#55
