### ISSUE TITLE
cannot import name 'MolScoreBenchmark' from 'molscore'

### ISSUE THREAD

**Issue by surendraphd** [Acellera/acegen-open#6]
Hi,
After following the installation setup and running the reinvent.py example code. I encountered the following error.
Can you please let know, the cause of error.

Thanks in advance..

(acegen) medicina@medicina:/media/Data/acegen-open$ python reinvent.py 
Error executing job with overrides: []
Traceback (most recent call last):
  File "/media/Data/acegen-open/reinvent.py", line 40, in <module>
    from molscore import MolScoreBenchmark
ImportError: cannot import name 'MolScoreBenchmark' from 'molscore' (/home/medicina/anaconda3/envs/acegen/lib/python3.10/site-packages/MolScore-1.0-py3.10.egg/molscore/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/Data/acegen-open/reinvent.py", line 68, in main
    raise RuntimeError(
RuntimeError: MolScore library not found, unable to create a scoring function. 

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by albertbou92** [comment]
Hello! Thanks a lot for pointing it out. I forgot to specify that the MolScoreBenchmark is a recent feature and is in the `develop` branch. 
So essentially you first need to `git checkout` to the `develop` branch and then do the same installation.
In the future will be part of the `main` branch. For now I will update the README.md with this info.

**Comment by surendraphd** [comment]
Hello,
Thank you for solving the issue. I did fresh installation and when I starts running the new job. I am receiving another error.
Can you please check this issue.

Thanks in advance..


(acegen) medicina@medicina:~/Downloads/acegen-open$ python reinvent.py
To use openeye scoring functions please install openeye and acquire a license
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/medicina/Downloads/acegen-open/reinvent.py", line 73, in main
    MSB = MolScoreBenchmark(
  File "/home/medicina/anaconda3/envs/acegen/lib/python3.10/site-packages/MolScore-1.0-py3.10.egg/molscore/manager.py", line 829, in __init__
    raise ValueError("No configs found to run, this could be due to include/exclude resulting in zero configs to run")
ValueError: No configs found to run, this could be due to include/exclude resulting in zero configs to run

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Calculating summary metrics
Preview of Results:
Empty DataFrame
Columns: []
Index: []
